version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: KarAmooziRoshan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    command: celery -A KarAmooziRoshan worker -l info
    depends_on:
      - db

  celery-beat:
    build: .
    command: celery -A KarAmooziRoshan beat -l info
    depends_on:
      - db

volumes:
  postgres_data:
