# Generated by Django 5.1.2 on 2024-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
