# Generated by Django 5.1.2 on 2024-11-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_report_delete_pdfreport_activitylog_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.report'),
        ),
    ]
